import type { Question, Scenario } from './types';

// Content contract shared with the avatar agent. NPC IDs stay stable so existing
// world reservations and Blender spawn manifests keep referring to the same actor.
const q = (
  id: string, kind: Question['kind'], japanese: string, meaning: string,
  task: string, modelAnswer: string, answerMeaning: string, reading: string, tip: string,
  options?: string[], correctIndex?: number,
): Question => ({ id, kind, japanese, meaning, task, modelAnswer, answerMeaning, reading, tip, options, correctIndex });

export const scenarios: Scenario[] = [
  {
    id: 'coffee', npcId: 'cafe_owner', title: 'Your first coffee order', name: 'Aiko',
    location: '喫茶店 · Coffee shop',
    description: 'Meet Aiko, order an iced coffee, choose the details, and pay. Answer in English or practise the Japanese equivalent.',
    questions: [
      q('welcome', 'roleplay', 'いらっしゃいませ。お一人ですか？', 'Welcome. Are you here alone?',
        'Tell Aiko you are here on your own.', 'はい、一人です。', 'Yes, just me.', 'Hai, hitori desu.',
        '一人（ひとり）means one person. English “Just me” also communicates the right idea.'),
      q('menu', 'meaning', 'メニューをどうぞ。', 'Here is the menu.',
        'What is Aiko offering you?', 'ありがとうございます。', 'Thank you.', 'Arigatō gozaimasu.',
        'メニュー means menu. After accepting it, say ありがとうございます.', ['The bill', 'The menu', 'A receipt'], 1),
      q('drink', 'roleplay', '何になさいますか？', 'What would you like?',
        'Order one coffee politely.', 'コーヒーを一杯お願いします。', 'One coffee, please.', 'Kōhī o ippai onegaishimasu.',
        '一杯（いっぱい）counts one cup. コーヒーをください is also a natural request; the example is not the only correct answer.'),
      q('temperature', 'meaning', 'ホットとアイス、どちらになさいますか？', 'Would you like hot or iced?',
        'Choose the reply asking for iced coffee.', 'アイスでお願いします。', 'Iced, please.', 'Aisu de onegaishimasu.',
        'アイス is iced; ホット is hot. Keep your drink choice clear.', ['ホットでお願いします。', 'アイスでお願いします。', 'お水をください。'], 1),
      q('size', 'fill', 'サイズはいかがなさいますか？', 'What size would you like?',
        'Complete the request: 小さいサイズを ____。', '小さいサイズをお願いします。', 'A small size, please.', 'Chiisai saizu o onegaishimasu.',
        'お願いします turns the item into a polite request.', ['お願いします', '行きます', '食べます'], 0),
      q('milk', 'roleplay', 'ミルクはお入れしますか？', 'Would you like milk?',
        'Ask for your coffee without milk.', 'ミルクなしでお願いします。', 'No milk, please.', 'Miruku nashi de onegaishimasu.',
        'なし means without. Do not lose the negative meaning when translating “No milk, please”.'),
      q('snack', 'politeness', 'ケーキもいかがですか？', 'Would you like cake too?',
        'Choose a polite way to decline the cake.', 'いいえ、結構です。ありがとうございます。', 'No, thank you.', 'Iie, kekkō desu. Arigatō gozaimasu.',
        'いいえ、結構です politely declines this offer. Adding a thank you softens the refusal.', ['ケーキを二つください。', 'いいえ、結構です。ありがとうございます。', 'もっとください。'], 1),
      q('confirm', 'roleplay', 'アイスコーヒーの小さいサイズ、ミルクなしですね。', 'A small iced coffee without milk, correct?',
        'Confirm that the order is correct.', 'はい、それでお願いします。', 'Yes, that is what I would like.', 'Hai, sore de onegaishimasu.',
        'それでお願いします means “That is what I would like”. Confirm only if the details match.'),
      q('payment', 'roleplay', 'お会計は五百円です。', 'Your total is 500 yen.',
        'Ask whether you can pay by card.', 'カードで払えますか？', 'Can I pay by card?', 'Kādo de haraemasu ka?',
        'で marks the method of payment. カードは使えますか is another natural way to ask.'),
      q('goodbye', 'roleplay', 'ありがとうございました。またお越しください。', 'Thank you. Please visit again.',
        'Thank Aiko and say you will come again.', 'ありがとうございました。また来ます。', 'Thank you. I will come again.', 'Arigatō gozaimashita. Mata kimasu.',
        'ありがとうございました thanks someone for a completed visit. また来ます means “I will come again”.'),
    ],
  },
  {
    id: 'market', npcId: 'shopkeeper', title: 'Fresh fruit at the market', name: 'Mei',
    location: '果物屋 · Fruit market',
    description: 'Meet Mei, ask what is in season, choose fresh fruit, and buy the right quantity. Practise prices and simple requests.',
    questions: [
      q('welcome', 'roleplay', 'いらっしゃいませ。何をお探しですか？', 'Welcome. What are you looking for?',
        'Tell Mei you are looking for fruit.', '果物を探しています。', 'I am looking for fruit.', 'Kudamono o sagashite imasu.',
        '果物（くだもの）means fruit. You can begin in English, then try the Japanese phrase.'),
      q('season', 'roleplay', '今日は桃とりんごがあります。', 'Today we have peaches and apples.',
        'Ask which fruit Mei recommends.', 'おすすめはどれですか？', 'Which one do you recommend?', 'Osusume wa dore desu ka?',
        'おすすめ means recommendation. どれ asks “which one” among the items in front of you.'),
      q('recommendation', 'meaning', '今は桃が旬です。甘くておいしいですよ。', 'Peaches are in season now. They are sweet and delicious.',
        'Which fruit is in season?', '桃が旬なんですね。', 'So peaches are in season.', 'Momo ga shun nan desu ne.',
        '桃（もも）is peach. 旬（しゅん）means in season.', ['Apples', 'Peaches', 'Bananas'], 1),
      q('price', 'roleplay', 'こちらの桃はいかがですか？', 'How about these peaches?',
        'Ask how much one peach costs.', '桃は一個いくらですか？', 'How much is one peach?', 'Momo wa ikko ikura desu ka?',
        '一個（いっこ）means one item. Make clear whether you are asking about one fruit or a whole bag.'),
      q('price-check', 'meaning', '桃は一個三百円です。', 'Peaches are 300 yen each.',
        'How much does one peach cost?', '一個三百円ですね。', 'It is 300 yen each, correct?', 'Ikko sanbyaku en desu ne.',
        '三百 is 300, pronounced さんびゃく. The price is per peach.', ['30 yen', '3,000 yen', '300 yen'], 2),
      q('quantity', 'fill', '何個になさいますか？', 'How many would you like?',
        'Complete an order for two peaches: 桃を ____ ください。', '桃を二個ください。', 'Two peaches, please.', 'Momo o niko kudasai.',
        '二個（にこ）means two items. 二つ（ふたつ）is also a useful general counter.', ['二個', '二時', '二人'], 0),
      q('ripeness', 'roleplay', '今日召し上がりますか？', 'Will you eat them today?',
        'Say yes, and ask for ripe peaches.', 'はい、今日食べます。熟した桃をお願いします。', 'Yes, I will eat them today. Ripe peaches, please.', 'Hai, kyō tabemasu. Jukushita momo o onegaishimasu.',
        '熟した（じゅくした）means ripe. Preserve both details: eating today and wanting ripe fruit.'),
      q('bag', 'politeness', '袋はご利用ですか？', 'Would you like a bag?',
        'Choose a polite reply declining the bag because you have your own.', '袋は結構です。マイバッグがあります。', 'No bag, thank you. I have my own bag.', 'Fukuro wa kekkō desu. Mai baggu ga arimasu.',
        '袋（ふくろ）means bag. State the refusal clearly, then explain that you brought one.', ['袋を二つください。', '袋は結構です。マイバッグがあります。', '袋はいくらですか？'], 1),
      q('total', 'meaning', '桃が二個で、合計六百円です。', 'For two peaches, the total is 600 yen.',
        'What is the total for your two peaches?', '六百円ですね。', 'It is 600 yen, correct?', 'Roppyaku en desu ne.',
        '六百 is 600, pronounced ろっぴゃく. Two peaches at 300 yen each total 600 yen.', ['300 yen', '600 yen', '6,000 yen'], 1),
      q('goodbye', 'roleplay', 'ありがとうございました。またどうぞ。', 'Thank you. Please come again.',
        'Thank Mei for helping you choose the fruit.', '選んでくださって、ありがとうございます。', 'Thank you for choosing them for me.', 'Erande kudasatte, arigatō gozaimasu.',
        '選ぶ（えらぶ）means choose. A simple ありがとうございます is also a polite way to finish.'),
    ],
  },
  {
    // Legacy ID retained until Ryan changes the shared world manifest.
    id: 'restaurant', npcId: 'local_guide', title: 'Dinner at a local restaurant', name: 'Haru',
    location: 'レストラン · Restaurant',
    description: 'Meet Haru, request a table, understand the menu, order dinner, and ask for the bill. Learn one useful exchange at a time.',
    questions: [
      q('table', 'roleplay', 'いらっしゃいませ。何名様ですか？', 'Welcome. How many people?',
        'Ask for a table for two.', '二人です。席はありますか？', 'There are two of us. Do you have a table?', 'Futari desu. Seki wa arimasu ka?',
        '二人（ふたり）means two people. “A table for two, please” is a valid English answer.'),
      q('reservation', 'meaning', 'ご予約はありますか？', 'Do you have a reservation?',
        'What is Haru asking about?', '予約はしていません。', 'I do not have a reservation.', 'Yoyaku wa shite imasen.',
        '予約（よやく）means reservation. This example reply says you do not have one.', ['A reservation', 'Your order', 'Your receipt'], 0),
      q('seat', 'roleplay', 'こちらの席へどうぞ。', 'Please take these seats.',
        'Thank Haru and ask for the menu.', 'ありがとうございます。メニューをお願いします。', 'Thank you. May I have the menu, please?', 'Arigatō gozaimasu. Menyū o onegaishimasu.',
        'Use two short sentences: acknowledge the help, then make the request.'),
      q('recommendation', 'roleplay', 'ご注文はお決まりですか？', 'Are you ready to order?',
        'Ask what Haru recommends.', 'おすすめの料理は何ですか？', 'What dish do you recommend?', 'Osusume no ryōri wa nan desu ka?',
        '料理（りょうり）means a dish or cooking. おすすめは何ですか also works here.'),
      q('set-menu', 'meaning', '焼き魚の定食がおすすめです。ご飯とみそ汁が付きます。', 'I recommend the grilled-fish set meal. It comes with rice and miso soup.',
        'What comes with the grilled fish?', 'ご飯とみそ汁が付くんですね。', 'So it comes with rice and miso soup.', 'Gohan to misoshiru ga tsukun desu ne.',
        '定食（ていしょく）is a set meal. ご飯 is rice; みそ汁 is miso soup.', ['Bread and coffee', 'Rice and miso soup', 'Noodles and cake'], 1),
      q('order', 'fill', '何になさいますか？', 'What would you like?',
        'Complete the order: 焼き魚の定食を一つ ____。', '焼き魚の定食を一つお願いします。', 'One grilled-fish set meal, please.', 'Yakizakana no teishoku o hitotsu onegaishimasu.',
        '一つ（ひとつ）means one. お願いします is a polite request ending.', ['帰ります', '寝ます', 'お願いします'], 2),
      q('drink', 'roleplay', 'お飲み物はいかがですか？', 'Would you like something to drink?',
        'Ask for water.', 'お水をお願いします。', 'Water, please.', 'Omizu o onegaishimasu.',
        'お水（おみず）is a polite way to say water. お水をください is natural too.'),
      q('repeat', 'politeness', 'ご注文を確認いたします。', 'Let me confirm your order.',
        'Choose a polite way to ask Haru to repeat slowly.', 'もう一度、ゆっくりお願いします。', 'Once more, slowly, please.', 'Mō ichido, yukkuri onegaishimasu.',
        'Ask for clarification whenever you need it. もう一度 means once more.', ['もう一度、ゆっくりお願いします。', '早くして。', 'わかった、わかった。'], 0),
      q('bill', 'roleplay', 'お食事はいかがでしたか？', 'How was your meal?',
        'Say it was delicious and ask for the bill.', 'おいしかったです。お会計をお願いします。', 'It was delicious. The bill, please.', 'Oishikatta desu. Okaikei o onegaishimasu.',
        'おいしかったです means it was delicious. お会計（おかいけい）means the bill or payment.'),
      q('goodbye', 'roleplay', 'ありがとうございました。またお待ちしております。', 'Thank you. We look forward to seeing you again.',
        'Thank Haru for the meal before leaving.', 'ごちそうさまでした。ありがとうございました。', 'Thank you for the meal. Thank you very much.', 'Gochisōsama deshita. Arigatō gozaimashita.',
        'ごちそうさまでした is a customary expression of thanks after a meal.'),
    ],
  },
];

export const scenarioForNpc = (npcId: string) => scenarios.find(s => s.npcId === npcId) ?? scenarios[0];
