import test from 'node:test';
import assert from 'node:assert/strict';
import { LessonEngine } from '../../lib/lesson/engine';
import { scenarios } from '../../lib/lesson/scenarios';
import type { Feedback } from '../../lib/lesson/types';
const feedback = (verdict: Feedback['verdict']): Feedback => ({ verdict, answer: 'test', explanation: '', japanese: '', reading: '', meaning: '' });
test('retries never farm points; a later correct spoken answer earns only missing rewards', () => {
  const engine = new LessonEngine(scenarios[0]);
  const id = engine.question.id;
  const ticket = engine.begin(id);
  engine.finish(ticket, feedback('try_again'));
  assert.equal(engine.state.rewards.points, 5);
  assert.equal(engine.finish(ticket, feedback('correct'), 'voice'), false);
  assert.equal(engine.state.rewards.points, 5);
  engine.retry(id);
  engine.finish(engine.begin(id), feedback('correct'), 'voice');
  assert.equal(engine.state.rewards.points, 20);
  assert.equal(engine.state.rewards.spoken, 1);
  assert.equal(engine.state.rewards.answered, 1);
  engine.retry(id);
  engine.finish(engine.begin(id), feedback('correct'), 'voice');
  assert.equal(engine.state.rewards.points, 20);
  assert.equal(engine.state.rewards.lastEarned, 0);
  assert.equal(engine.state.rewards.correct, 1);
});
test('quiz totals distinguish attempts from correct questions and reset with a fresh lesson', () => {
  const source = scenarios[0];
  const quiz = source.questions.find(question => question.options)!;
  const engine = new LessonEngine({ ...source, questions: [quiz] });
  engine.finish(engine.begin(quiz.id), feedback('try_again'));
  assert.equal(engine.state.rewards.quizzesAnswered, 1);
  assert.equal(engine.state.rewards.quizzesCorrect, 0);
  engine.retry(quiz.id);
  engine.finish(engine.begin(quiz.id), feedback('correct'));
  engine.next(quiz.id);
  assert.equal(engine.state.rewards.quizzesAnswered, 1);
  assert.equal(engine.state.rewards.quizzesCorrect, 1);
  assert.equal(engine.state.rewards.spoken, 0);
  assert.equal(engine.state.rewards.points, 15);
  assert.equal(engine.state.completed, true);
  assert.equal(new LessonEngine(source).state.rewards.points, 0);
});
