import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createAvatar,disposeAvatarTemplate} from '../../lib/characters/avatar';
async function asset(path:string){const b=await readFile(new URL('../../public/models/'+path,import.meta.url));return new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');}
test('exported ride assets have metre scale, ground origins and independently rotating wheels',async()=>{for(const kind of ['scooter','skateboard']as const){const a=await asset(`vehicles/${kind}.glb`);a.scene.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(a.scene);assert(Math.abs(b.min.y)<.002);assert(b.max.y<(kind==='scooter'?1.5:.19));let triangles=0;let wheels=0;a.scene.traverse(o=>{if(o.name.startsWith('Wheel_')){wheels++;assert(Math.abs(o.position.y-(kind==='scooter'?.22:.045))<.001);assert(o.quaternion.angleTo(new THREE.Quaternion())<.001);}if(o instanceof THREE.Mesh){triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;assert([...o.geometry.attributes.position.array].every(Number.isFinite));}});assert.equal(wheels,kind==='scooter'?2:4);assert(triangles<(kind==='scooter'?12000:4000));}});
test('riding hands meet scooter grips across avatar heights; dismount restores authored rig',async()=>{const a=await asset('characters/komorebi_npc.glb');try{for(const height of [1.5,1.7,1.9]){const rider=createAvatar(a,{height});const original=rider.model.getObjectByName('hips')!.position.clone();rider.setRiding({kind:'scooter',speed:5});for(let i=0;i<60;i++)rider.update(1/60);for(const [side,x]of [['L',.28],['R',-.28]]as const){const hand=rider.getSocket(`socket_hand_${side}`);assert(hand.distanceTo(new THREE.Vector3(x,1.12,.5))<.025,`${height} ${side} grip ${hand.toArray()}`);}rider.setRiding({kind:'skateboard',speed:4});rider.update(.05);assert.equal(rider.riding,'skateboard');for(const side of ['L','R']){const p=rider.model.getObjectByName(`${side}_foot`)!.getWorldPosition(new THREE.Vector3());assert(p.y>.2&&p.y<.3);assert(Math.abs(p.z)>.2);}rider.setRiding(null);rider.play('Idle',{fade:0,restart:true});rider.update(0);assert(rider.model.getObjectByName('hips')!.position.distanceTo(original)<.02);rider.dispose();}}finally{disposeAvatarTemplate(a);}});
