import test, { before } from 'node:test';
import assert from 'node:assert/strict';
import { WorldRoom } from '../../lib/world/room';
import { initWorldPhysics } from '../../lib/world/physics';
import { KYOTO_ENVIRONMENT, KYOTO_NPCS } from '../../lib/world/kyoto';
import { environmentSchema, type VehicleKind } from '../../lib/world/schema';
import { VEHICLE_CONFIG } from '../../lib/world/vehicle-contract';
before(initWorldPhysics);
function fixture(kind: VehicleKind='scooter') {return environmentSchema.parse({id:'rides',revision:'test',name:'Rides',assetUrl:null,spawn:[0,0,0],bounds:{min:[-20,-4,-20],max:[20,8,20]},colliders:[],npcSpawns:{},vehicleSpawns:[{id:'ride',kind,position:[0,0,1],yaw:0}]});}
function drive(room:WorldRoom, seconds:number, direction:[number,number], start=0){for(let i=0;i<seconds*20;i++){const n=start+i;room.command('a',{type:'move',direction,yaw:Math.atan2(...direction),sequence:n},n*50);room.tick(.05,n*50);}}
test('one rider wins a mount race, and spectators cannot dismount their ride',t=>{const r=new WorldRoom('rides',fixture(),[]);t.after(()=>r.dispose());r.join('a','A');r.join('b','B');assert.equal(r.command('a',{type:'mount-vehicle',vehicleId:'ride'}),null);assert.match(r.command('b',{type:'mount-vehicle',vehicleId:'ride'})!,/already has/);assert.match(r.command('b',{type:'dismount-vehicle'})!,/not riding/);assert.equal(r.snapshot().vehicles[0].riderId,'a');});
for(const kind of ['scooter','skateboard'] as const)test(`${kind} accelerates to its own speed cap, brakes, and leaves its last position`,t=>{const r=new WorldRoom('rides',fixture(kind),[]);t.after(()=>r.dispose());r.join('a','A');r.command('a',{type:'mount-vehicle',vehicleId:'ride'});drive(r,.05,[0,1]);const first=r.snapshot().vehicles[0].speed;assert(first>0&&first<.5);drive(r,2,[0,1],1);const s=r.snapshot();assert(s.vehicles[0].speed<=VEHICLE_CONFIG[kind].maxSpeed);assert(s.vehicles[0].speed>VEHICLE_CONFIG[kind].maxSpeed-.1);assert.deepEqual(s.players[0].position,s.vehicles[0].position);drive(r,1,[0,0],100);assert.equal(r.snapshot().vehicles[0].speed,0);const parked=r.snapshot().vehicles[0].position;assert.equal(r.command('a',{type:'dismount-vehicle'}),null);assert.equal(r.snapshot().players[0].vehicleId,null);assert.deepEqual(r.snapshot().vehicles[0].position,parked);assert(Math.hypot(r.snapshot().players[0].position[0]-parked[0],r.snapshot().players[0].position[2]-parked[2])>.7);});
test('riding blocks emotes and NPC interaction, and disconnect releases ownership',t=>{const r=new WorldRoom('rides',fixture(),[]);t.after(()=>r.dispose());r.join('a','A');assert.match(r.command('a',{type:'mount-vehicle',vehicleId:'missing'})!,/Unknown/);r.command('a',{type:'mount-vehicle',vehicleId:'ride'});assert.match(r.command('a',{type:'emote',name:'wave'})!,/Dismount/);assert.match(r.command('a',{type:'interact',npcId:'guide'})!,/Dismount/);r.leave('a');assert.equal(r.snapshot().vehicles[0].riderId,null);r.join('b','B');assert.equal(r.command('b',{type:'mount-vehicle',vehicleId:'ride'}),null);});
test('all six Kyoto parking places are supported, and each ride mounts/dismounts using real city colliders',t=>{for(const spawn of KYOTO_ENVIRONMENT.vehicleSpawns!){const r=new WorldRoom('parking',{...KYOTO_ENVIRONMENT,spawn:spawn.position},KYOTO_NPCS);t.after(()=>r.dispose());r.join('a','A');assert.equal(r.command('a',{type:'mount-vehicle',vehicleId:spawn.id}),null,spawn.id);assert.equal(r.command('a',{type:'dismount-vehicle'}),null,spawn.id);assert(r.snapshot().players[0].position[1]>.2);}});
test('mounting through a wall and mounting from far away are rejected',t=>{const env=fixture();env.vehicleSpawns![0].position=[0,0,1.9];env.colliders=[{min:[-3,0,.4],max:[3,3,.6]}];const r=new WorldRoom('blocked',env,[]);t.after(()=>r.dispose());r.join('a','A');assert.match(r.command('a',{type:'mount-vehicle',vehicleId:'ride'})!,/blocked/);const distant=fixture();distant.vehicleSpawns![0].position=[0,0,8];const d=new WorldRoom('far',distant,[]);t.after(()=>d.dispose());d.join('a','A');assert.match(d.command('a',{type:'mount-vehicle',vehicleId:'ride'})!,/within 2/);});
test('a ride stops at an unsupported ledge without falling or teleporting',t=>{const env=fixture();env.spawn=[0,.011,0];env.vehicleSpawns![0].position=[0,.011,1];env.physics={colliders:[{name:'platform',position:[0,-.2,0],halfExtents:[4,.2,4],quaternion:[0,0,0,1]}],stepHeight:.22,maxSlopeDegrees:35,groundSnap:.3,gravity:-9.81};const r=new WorldRoom('ledge',env,[]);t.after(()=>r.dispose());r.join('a','A');assert.equal(r.command('a',{type:'mount-vehicle',vehicleId:'ride'}),null);drive(r,4,[0,1]);const v=r.snapshot().vehicles[0];assert(v.position[2]>2&&v.position[2]<3.5,JSON.stringify(v));assert(v.position[1]>-.02);assert.equal(v.speed,0);assert.equal(r.command('a',{type:'dismount-vehicle'}),null);});
test('riding sweeps stop at solid walls',t=>{const env=fixture();env.colliders=[{min:[-5,0,5],max:[5,4,5.2]}];const r=new WorldRoom('wall',env,[]);t.after(()=>r.dispose());r.join('a','A');r.command('a',{type:'mount-vehicle',vehicleId:'ride'});drive(r,5,[0,1]);assert(r.snapshot().vehicles[0].position[2]<4.11);assert.equal(r.snapshot().vehicles[0].speed,0);});
