/* eslint-disable */
// Generated by Wrangler by running `wrangler types multiplayer/bindings.d.ts --config multiplayer/wrangler.jsonc --env-interface KyotoWorkerEnv --include-runtime=false --strict-vars=false` (hash: 8f104aaeb3f9b833dc890c3511abbd4a)
interface __BaseEnv_KyotoWorkerEnv {
	WORLD_ADMISSION: RateLimit;
	WORLD_TICKET_SECRET: string;
	WORLD_ALLOWED_ORIGINS: string;
	KYOTO_ROOMS: DurableObjectNamespace<import("./worker").KyotoRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "KyotoRoom";
	}
	interface Env extends __BaseEnv_KyotoWorkerEnv {}
}
interface KyotoWorkerEnv extends __BaseEnv_KyotoWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WORLD_TICKET_SECRET" | "WORLD_ALLOWED_ORIGINS">> {}
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}